import type { Metadata } from "next";
import { Inter, Zeyada, Abril_Fatface } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const abril = Abril_Fatface({ subsets: ["latin"], weight:'400', variable: '--font-abril'});
const zeyada = Zeyada({ subsets: ["latin"], weight:'400', variable: '--font-zeyada' });

export const metadata: Metadata = {
  title: "Oh My Gin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[--pale] ${inter.variable} ${abril.variable} ${zeyada.variable}`}>
        {/* <Header func={''}/> */}
        {children}
        </body>
    </html>
  );
}
